### ISSUE TITLE
Make Spyral work without Greenlets

### ISSUE THREAD

**Issue by acbart** [platipy/spyral#42]
Currently, loading spyral without greenlets on the system will result in a crash. But this shouldn't be a necessary feature, it's meant to be optional. I propose to rework the Scene's importing of Actors such that it only throws a warning if greenlets aren't installed. If you attempt to instantiate an Actor, however, the game should exception out.

**Comment by icarito** [comment]
I think this is the way it's currently working, maybe close this one.

**Comment by icarito** [comment]
Perhaps do the same with parsley?

**Comment by acbart** [comment]
Yep, this issue wasn't closed. Thanks for the catch (and parsley should be removed, I think :).
