### ISSUE TITLE
Maybe a mailing list?

### ISSUE THREAD

**Issue by icarito** [platipy/spyral#64]
For things like "check my new game out" or newbie questions...

BTW, check our new game out!
http://activities.sugarlabs.org/es-ES/sugar/addon/4744/

Also competed in pyweek:
https://pyweek.org/e/Ecollusion/

Warm regards,
Sebastian

**Comment by acbart** [comment]
It's pretty quiet at the moment, but we have a Google Group for Spyral/Platipy as of a couple months ago!

https://groups.google.com/forum/#!forum/platipy

Can't wait to try your game, looks very nifty!
