### ISSUE TITLE
Attend Sugar Camp Chía 2014

### ISSUE THREAD

**Issue by icarito** [platipy/spyral#66]
Hi,
We are organising an event called "Sugar Camp" where we invite the local and international community to get together and design+hack games around Sugar, kind of like a Marathon.
In this opportunity we will work on the games written for the Artisan Videogame Workshop, with the children, educators, volunteers, facilitators, artists and citizens that are interested in education and Free Software.

Needless to say our games use Spyral!

I would really be happy if you could come over to Bogota on the 17,18,19th of July.
More info on the event: http://camp.laboratoriosazucar.org/

Let me know if you'd like to come and how we can help.

**Comment by icarito** [comment]
Would've been nice to have you! Hopefully there will be a next opportunity.

**Comment by acbart** [comment]
Indeed! Difficult to get travel time and funds at this phase of my life :)
